# Universe should always be 'vanilla' unless you know explicitly what you're doing
universe = vanilla

# this sets the environment variables of the login environment to the compute node environment
# generally, you will want to leave this set to true
getenv = true

# this is the command or program you are running. 
# common executables and their locations are:
# R: /usr/bin/Rscript
# matlab: /opt/MatlabR2018a/bin/matlab 
# python 2.7.3: /opt/python/bin/python 
# python 3.4.4: /opt/python3.4/bin/python 
# many other applications can be found in /opt

executable = /usr/bin/Rscript  
arguments = test.R

# this is the name and location of the Condor logs for your job. This will show details of what condor itself is doing in relation to your job, but not the output of your job
log = $(Cluster).log

# this is the name and location of the actual output from your job. 
# output will contain whatever would've been sent to the screen (aka STDOUT) 
# error will contain any errors generated by your application (aka STDERR)
# the variable $(cluster) will generate one number per run of "condor_submit"
# the variable $(process) will generate a unique number for every job generated within this script, starting at zero
output = $(Cluster).$(process).out
error = $(cluster).$(Process).error

# these options will notify the email listed below if the job errors out or when it completes
# comment or delete these lines if you do not wish to get an email
# you will get an email for each instance of your job, so if you spawn 50 jobs you will get 50 emails.
notification = error
notification = complete
notify_user = username@gatech.edu

# If you need a specific amount of memory, uncomment the line below and change the number to the minimum amount of RAM you need for your job. This number is in megabytes.
# request_memory=2048

# if you need to run this more than once, enter the number of copies after the queue command
# for every copy spawned, the variable $(process) will increment by one, starting at zero. 
# if you only wish this to run once, leave the queue command with no number. 
# the queue command is REQUIRED 
queue
